# Generated by Django 2.2.7 on 2019-11-27 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_movie_score_expected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='score_expected',
        ),
        migrations.AddField(
            model_name='movie',
            name='score_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ScoresExpected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='score_exp_users',
            field=models.ManyToManyField(related_name='score_exp_movies', through='movies.ScoresExpected', to=settings.AUTH_USER_MODEL),
        ),
    ]
