# Generated by Django 2.2.7 on 2019-11-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20191127_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresexpected',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
