# Generated by Django 2.2.7 on 2019-11-27 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='score_total',
        ),
    ]
