# Generated by Django 2.2.7 on 2019-11-22 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191122_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(default=0)),
                ('reference_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to=settings.AUTH_USER_MODEL)),
                ('similar_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='similar_users',
            field=models.ManyToManyField(blank=True, related_name='reference_users', through='accounts.Similarity', to=settings.AUTH_USER_MODEL),
        ),
    ]
